### ISSUE TITLE
Set a different upstream manager module

### ISSUE THREAD

**Issue by Tieske** [openresty/lua-resty-upstream-healthcheck#11]
The module currently relies on the `ngx.upstream` module for managing the upstreams.

Unfortunately we cannot use that module for our usecase. See [discussion here](https://github.com/Mashape/kong/issues/157#issuecomment-172057506)

Would you accept a PR to set the module explicitly, making it configurable? so I won't have to fork the code.

If so, should it be a setting on module level (in an upvalue, shared by all checkers spawned), or a setting per spawned checker. Imho the latter, but please share your thoughts.

**Comment by agentzh** [comment]
@Tieske That makes sense. I prefer passing the concrete upstream object via an argument option too.

**Comment by Tieske** [comment]
Ok, Thx for the heads up. I'll work on a PR. Will you be merging #10? so I can base the new PR on that (otherwise it will surely deliver some conflicts)

**Comment by Tieske** [comment]
closing this in favor of #12
