### ISSUE TITLE
bad local

### ISSUE THREAD

**Issue by Tieske** [openresty/lua-resty-upstream-healthcheck#16]
The `nthr`variable here; https://github.com/openresty/lua-resty-upstream-healthcheck/blob/master/lib/resty/upstream/healthcheck.lua#L322 

Should not be a local. It shadows the outer scope. as such the check slightly further down, where we wait for all spawned threads to finish will never run, because the outer scoped `nthr` will still be `nil`.

**Comment by doujiang24** [comment]
@Tieske Nice catch :)

**Comment by Tieske** [comment]
It gave me a nasty sync issue, took me an hour and a half to track it down. I'll try a PR once I'm done with my current stuff

**Comment by agentzh** [comment]
@Tieske Thanks for the report! Will you please create a PR with a corresponding test case for it? Thanks!

**Comment by thibaultcha** [comment]
Just opened #59 which comes with a test case and additional fixes.
