### ISSUE TITLE
attempt to index field 're' (a nil value)

### ISSUE THREAD

**Issue by chainkite** [openresty/lua-resty-upstream-healthcheck#21]
error.log
```
2016/08/15 14:06:34 [error] 4566#0: init_worker_by_lua error: /usr/local/openresty/lualib/resty/upstream/healthcheck.lua:9: attempt to index field 're' (a nil value)
stack traceback:
	/usr/local/openresty/lualib/resty/upstream/healthcheck.lua:9: in main chunk
	[C]: in function 'require'
	init_worker_by_lua:2: in main chunk
```

Am I missing some lua dependencies?

**Comment by agentzh** [comment]
@chainkite What version of ngx_lua module or OpenResty bundle are you using? Please try the latest OpenResty bundle on your side (the latest version is 1.9.15.1).

Also, please provide the minimal code and config example that can reproduce the problem on our side. Thank you.

**Comment by agentzh** [comment]
@chainkite `ngx.re.find` should be the standard Lua API provided by ngx_lua:

https://github.com/openresty/lua-nginx-module/#ngxrefind

It's strange that it's missing on your side.

**Comment by chainkite** [comment]
@agentzh I am using the latest OpenResty verson 1.9.15.1

Is ngx_lua already bundled in `openresty-1.9.15.1.tar.gz` I downloaded from https://openresty.org/en/download.html ?

I installed openresty `--with-stream`. I am not sure whether it matters.

**Comment by agentzh** [comment]
@chainkite OpenResty always includes ngx_lua. And from your error log message, the "init_worker_by_lua error:" message is indeed generated from ngx_lua (otherwise nginx has no idea about that directive).

The `--with-stream` option is irrelevant.

Let me repeat: "please provide the minimal code and config example that can reproduce the problem on our side. Thank you."

**Comment by agentzh** [comment]
@chainkite Also: are you using any other `./configure` options beside `--with-stream`? Or are you using any other Lua libraries than the ones shipped with OpenResty itself?

**Comment by agentzh** [comment]
@chainkite Looks like something clobbers away `ngx.re` while other ngx_lua's Lua API functions like `ngx.socket.tcp` and `ngx.log` work just fine. The first 9 lines in `healthcheck.lua` are as follows:

```lua
local stream_sock = ngx.socket.tcp
local log = ngx.log
local ERR = ngx.ERR
local INFO = ngx.INFO
local WARN = ngx.WARN
local DEBUG = ngx.DEBUG
local str_find = string.find
local sub = string.sub
local re_find = ngx.re.find
```

The error happens when the execution flow reaches the 9th line above (the last line quoted).

**Comment by chainkite** [comment]
@agentzh Sorry, didn't notice email pop3 crashed these days. 

I guess the `ngx.re` referring to `http_rewrite_module`... if so, that explains...

I exclude `http_rewrite_module` because I am not able to install `PCRE` on my machine. Some required dependencies of `PCRE` on my machine need upgrade and will stop many other services.

```
configure --without-http_rewrite_module --with-stream
make
make install
```

nginx.conf
```
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}

stream {
    upstream graylog_udp {
        server host1:12202;
        server host2:12202 backup;
    }

    server {
        listen 12202 udp;
        proxy_pass graylog_udp;
        proxy_timeout 1s;
        proxy_responses 1;
    }

}


http {
    lua_package_path "/usr/local/openresty/lualib/resty/?.lua;/usr/local/openresty/lualib/resty/upstream/?.lua;;";

    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    upstream graylog_web {
        server host1:9000;
        server host2:9000;
    }

    upstream graylog_rest {
        server host1:12900;
        server host2:12900;
    }

    lua_shared_dict healthcheck 64k;

    init_worker_by_lua_block {
        local hc = require "resty.upstream.healthcheck"
        local ok, err = hc.spawn_checker {
            shm = "healthcheck",
            upstream = "graylog_rest",
            type = "http",
            http_req = "GET /system/lbstatus.txt HTTP/1.1\r\nHost: graylog_rest\r\n\r\n",
            interval = 1000,
            timeout = 5000,
            fall = 1,
            rise = 2,
            valid_statuses = {200, 302},
            concurrency = 10
        }
        if not ok then
            ngx.log(ngx.ERR, "failed to spawn health checker: ", err)
            return
        end
    }

    server {
        listen      12900;
        server_name localhost;

        access_log  off;

        location / {
            proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header    Host $http_host;
            proxy_pass          http://graylog_rest/;

            #health_check interval=3s uri=/system/lbstatus match=statusok;
        }
    }

    server {
        listen       9394 default_server;
        server_name  localhost;

        charset utf-8;

        access_log  off;

        location / {
            proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header    X-Graylog-Server-URL http://localhost:12900;
            proxy_set_header    Host $http_host;
            proxy_pass          http://graylog_web;

            #health_check interval=3s uri=/system/lbstatus port=12900 match=statusok;
        }

        location = /status {
            default_type text/plain;
            content_by_lua_block {
                local hc = require "resty.upstream.healthcheck"
                ngx.say("Nginx Worker PID: ", ngx.worker.pid())
                ngx.print(hc.status_page())
            }
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }

}
```

**Comment by agentzh** [comment]
@chainkite That explains. Disabling ngx_http_rewrite_module also disables the PCRE library in your nginx or openresty build while the `ngx.re` API requires the PCRE library.

Next time you report a problem, please always provide as many details as possible up front (including your complete `./configure` command line). Otherwise what a waste of our time! ;)
