### ISSUE TITLE
Support for specifying custom port

### ISSUE THREAD

**Issue by bompus** [openresty/lua-resty-upstream-healthcheck#28]
Would it be possible to support the following?

type = "http",
port = 80

This would be a reasonable workaround for those needing support for SSL backends, as long as they also listen on port 80, it's a good enough health check for me, and should be much easier to implement than adding type = "https"

**Comment by agentzh** [comment]
@bompus It's not possible since the servers defined in `upstream {}` already have port numbers (either explicitly or implicitly). Overriding port numbers with force is too hacky to be accepted.
