### ISSUE TITLE
健康检测失败

### ISSUE THREAD

**Issue by ghdjl** [openresty/lua-resty-upstream-healthcheck#32]
你好，我用的是0.04的版本，以下是我的nginx的健康检测配置
--------------------------------------------------------------------------------------------------------------
    ok, err = hc.spawn_checker{
        shm = "healthcheck",
        upstream = "dlv-business-service",
        type = "http",
        http_req = "GET /dlv-business-service HTTP/1.0\r\nHost: dlv-business-service\r\n\r\n",
        interval = 5000,
        timeout = 3000,
        fall = 5,
        rise = 3,
        valid_statuses = {200, 302, 304},
        concurrency = 10,
    }
--------------------------------------------------------------------------------------------------------------
upstream中有一个节点异常，但是lua-resty-upstream-healthcheck模块检测结果是正常的；但我将该节点的应用完全停止时，检测结果就是异常的了。

简而言之，lua-resty-upstream-healthcheck模块只实现了IP端口的检测，没有实现http检测，这种情况偶尔会出现，请问可能是什么原因导致的呢？

**Comment by ghdjl** [comment]
配置中 valid_statuses中我填的是 200,302,304，但是realserver 503的状态被nginx认为的正常的状态

**Comment by agentzh** [comment]
Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.
