### ISSUE TITLE
Init error using config as given in synopsis section of README

### ISSUE THREAD

**Issue by whatacold** [openresty/lua-resty-upstream-healthcheck#8]
The error msg is `[error] 9595#0: init_worker_by_lua error: init_worker_by_lua:11: function arguments expected near '.'`

And it seems like it's caused by this comment line: ` -- then you should write this instead: http_req = "GET /status HTTP/1.0\r\nHost: foo.com\r\n\r\n",`, I think it's a trial issue but I failed to fix this :-(, as I'm new to both OpenResty and Lua.

**Comment by agentzh** [comment]
@whatacold Please provide a minimal and self-contained configuration example that I can easily reproduce it on my side. BTW, please always provide the version number of OpenResty you're using when reporting issues. Thank you.

**Comment by agentzh** [comment]
@whatacold Never mind. I see what is going on now :) Thanks for the report!

**Comment by whatacold** [comment]
@agentzh OK, I'll provide the configuration example and version number next time, sorry for the inconvenience.

**Comment by agentzh** [comment]
@whatacold I've fixed the examples in the docs by migrating to the new `*_by_lua_block` directives. Will you please try the new example on your side? BTW, you need at least OpenResty 1.9.3.2 (or ngx_lua 0.9.19) for it.

**Comment by whatacold** [comment]
@agentzh Thanks. As my current version OpenResty is 1.9.3.1 and it's a bit late now, I'll try it tomorrow with version 1.9.3.2 and report back.

**Comment by agentzh** [comment]
@whatacold Thanks! No hurry :)

**Comment by whatacold** [comment]
@agentzh The new example configurations works,  with latest release 1.9.3.2.
Thanks.

**Comment by agentzh** [comment]
@whatacold Cool, thanks for the feedback. I'm closing this.
