### ISSUE TITLE
Test Case failures 

### ISSUE THREAD

**Issue by HelloWorld521** [openresty/lua-resty-upstream-healthcheck#94]
Test case 14 failed to be executed

Error: 
![image](https://user-images.githubusercontent.com/17756640/201565414-85d2b766-476f-47fc-9917-3a7a8338248f.png)
The IPv6 format is inconsistent

The linux kernel simplifies IPv6，Can we modify this use case？

system:
![image](https://user-images.githubusercontent.com/17756640/201565542-da2e7cb1-f7cb-4495-9e1a-8bb050e88965.png)

**Comment by zhuizhuhaomeng** [comment]
@HelloWorld521 Would you please create a PR for this?

**Comment by HelloWorld521** [comment]
@zhuizhuhaomeng I found that the master branch has been changed，I use v0.0.6.
Thank you for your reply
